# Generated by Django 5.0.1 on 2024-01-20 00:17

import django.db.models.fields
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_no', models.IntegerField(blank=True, null=True)),
                ('lead_source', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('interested_in', models.CharField(choices=[('Land', 'Land'), ('Apartment', 'Apartment')], default='Land', max_length=20)),
                ('uploaded_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_time', models.DateField(default=django.utils.timezone.now)),
                ('follow_up_time', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descriptions', models.TextField(blank=True, max_length=500, null=True)),
                ('contacted', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Prospective', 'Prospective'), ('Visited', 'Visited'), ('Confirmed', 'Confirmed'), ('Sold', 'Sold'), ('Bad', 'Bad')], default='Normal', max_length=20)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, related_name='assigned_member', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
