# Generated by Django 5.0.1 on 2024-01-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='target',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_for',
        ),
        migrations.RemoveField(
            model_name='target',
            name='type',
        ),
        migrations.RemoveField(
            model_name='target',
            name='unit',
        ),
        migrations.DeleteModel(
            name='TargetType',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
